version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - ${POSTGRES_DATA_DIRECTORY}:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

  roles-app:
    build:
      context: .
    container_name: roles-app
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB_NAME}
      - DATABASE_USERNAME=${POSTGRES_USERNAME}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: