version: 2
executorType: machine
jobs:
  build:
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # run tests!
      - run: ./gradlew build