CREATE TABLE USER_DETAIL
(
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSWORD_HASH VARCHAR(100),
    PASSWORD_SALT VARCHAR(100),
    CONSTRAINT USER_DETAILS_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE ROLE (
  NAME VARCHAR(100),
  ORDER_NUMBER VARCHAR(100),
  CONSTRAINT ROLE_PK PRIMARY KEY (NAME)
);

CREATE TABLE USER_ROLE (
  USER_EMAIL VARCHAR(100),
  ROLE_NAME VARCHAR(100),
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_EMAIL, ROLE_NAME),
  CONSTRAINT ROLE_EMAIL_FK FOREIGN KEY (USER_EMAIL) REFERENCES USER_DETAIL(EMAIL),
  CONSTRAINT ROLE_NAME_FK FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(NAME)
);

INSERT INTO USER_DETAIL (EMAIL, NAME, SURNAME, PASSWORD_HASH, PASSWORD_SALT) VALUES ('admin@roles.org', 'admin', 'admin', 'E9D2973B796BC7F766D03160E174B6DDC390CEE7', 'salt');

INSERT INTO ROLE (NAME, ORDER_NUMBER) VALUES ('ADMIN', 0);
INSERT INTO ROLE (NAME, ORDER_NUMBER) VALUES ('REVIEWER', 1);
INSERT INTO ROLE (NAME, ORDER_NUMBER) VALUES ('USER', 2);

INSERT INTO USER_ROLE (USER_EMAIL, ROLE_NAME) VALUES ('admin@roles.org', 'ADMIN');